### ISSUE TITLE
Ambiguity about CancerGram-analysis/reports/data/benchmark_res.csv

### ISSUE THREAD

**Issue by low0621** [BioGenies/CancerGram-analysis#1]
Hello, I'm trying to interpret the figure from the [report](https://github.com/BioGenies/CancerGram-analysis/blob/master/reports/data/benchmark_res.csv)
However, I have a little question about the software column
Could you explain what's the difference among "CancerGram", "CancerGram on AntiCP dataset", "CancerGramMC" and "CancerGramMC on AntiCP dataset"
![image](https://user-images.githubusercontent.com/20962037/104989900-69951f80-5a56-11eb-8fca-b2d9a4907b2e.png)
Specifically speaking, does the difference come from different dataset?
I consider that the software "CancerGram" is training on your own training dataset, which includes ACP, AMP and non ACP/non AMP, while the software "CancerGram on AntiCP dataset" is training on main dataset of "AntiCP2.0", which only includes ACP and AMP.
By the way, does "MC" stand for "multi-class"?

Thanks a lot

**Comment by ksidorczuk** [comment]
Hi, 
Yes, the differences come from different datasets and model architectures. 
'CancerGram' means a binary model trained on our own datasets (ACP/AMP or ACP/negative) and 'CancerGram on AntiCP dataset' corresponds to binary models trained on datasets from AntiCP 2.0 (the main dataset for ACP/AMP prediction and alternate for ACP/negative prediction). 
'MC' does indeed stand for a multi-class model, so 'CancerGramMC' is a multi-class model trained on our datasets and 'CancerGramMC on AntiCP dataset' is a multi-class model trained on AntiCP 2.0 datasets. 
To compare performance of the multi-class models with the binary ones, we binarized their predictions.

**Comment by low0621** [comment]
Thank you so much
